# Generated by Django 4.2 on 2023-04-17 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('short_description', models.TextField()),
                ('technology', models.CharField(max_length=20)),
                ('image', models.FilePathField(path='/img')),
                ('long_description', models.TextField()),
                ('website', models.TextField()),
                ('github', models.TextField()),
                ('appstore', models.TextField()),
                ('playstore', models.TextField()),
            ],
        ),
    ]
